[bot]
prefixes = ["-", "d!"]
description = """Bot for dOGbone!"""
playing = "2.0.0"
commands_are_case_insensitive = true

[database]
# A postgreSQL database to store information about users, channels, and guilds
# Please ensure the database exist before loading the database modules
# Quick Start : https://medium.com/coding-blocks/creating-user-database-and-adding-access-on-postgresql-8bfcd2f4a91e
enable = "true"
host = "127.0.0.1"
port = "5432"
user = "dog"
password = "Dsb!2020"
database = "dogbot"

[auth.discord]
# Your bot token. You can find it on the Bot page of the Developper portal
token = "ODA3NjkwMzI2NzAwNDU4MDA1.YB7qPA.ETN7LPVHYUp8uV2Vm0N6kJ7gke8"

[cogs]
# Names of cogs to load. Usually cogs.file_name_without_py
cogs_to_load = ['jishaku', 'cogs.error_handling', 'cogs.background_loop', 'cogs.support_server_commands', 'cogs.database_commands', 'cogs.utility', 'cogs.rest_api', "cogs.fun"]

[cogs.SupportServerCommands]
# That's the ID of your server where the command will be ran
support_server_id = 778757191770308628
# ID of an empty channel that will be used as a status dashboard.
status_channel_id = 830604398996357160